// Generated by CoffeeScript 1.6.2
(function() {
  var Drawer, btnleft, btnright, drawer, toggleLeft, toggleRight;

  Drawer = require('drawer');

  drawer = new Drawer(document.querySelector('.drawer'));

  window.drawer = drawer;

  toggleLeft = function(e) {
    drawer.toggleFirst();
    e.stopPropagation();
    return e.preventDefault();
  };

  toggleRight = function(e) {
    drawer.toggleSecond();
    e.stopPropagation();
    return e.preventDefault();
  };

  btnleft = document.getElementById('btnleft');

  btnright = document.getElementById('btnright');

  btnleft.addEventListener('click', toggleLeft);

  btnleft.addEventListener('touchstart', toggleLeft);

  btnright.addEventListener('click', toggleRight);

  btnright.addEventListener('touchstart', toggleRight);

}).call(this);
